#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_Backend.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PROYECTOWEBFINALV2")]
	public partial class conexionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public conexionDataContext() : 
				base(global::Proyecto_Final_Backend.Properties.Settings.Default.PROYECTOWEBFINALV2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public conexionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spObtenerFeedback")]
		public ISingleResult<spObtenerFeedbackResult> spObtenerFeedback()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spObtenerFeedbackResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spObtenerReservas")]
		public ISingleResult<spObtenerReservasResult> spObtenerReservas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spObtenerReservasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spRegistrarUsuario")]
		public int spRegistrarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string rol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, correo, contrasena, rol);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spObtenerFactura")]
		public ISingleResult<spObtenerFacturaResult> spObtenerFactura()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spObtenerFacturaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spIniciarSesion")]
		public ISingleResult<spIniciarSesionResult> spIniciarSesion()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spIniciarSesionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertarReserva")]
		public int spInsertarReserva([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha_reserva, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numero_personas)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fecha_reserva, numero_personas);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertarFactura")]
		public int spInsertarFactura([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numeroMesa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string listaPlatos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string listaPrecios, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,2)")] System.Nullable<decimal> total)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numeroMesa, listaPlatos, listaPrecios, total);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertarFeedback")]
		public int spInsertarFeedback([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string comentario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> calificacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), comentario, calificacion);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class spObtenerFeedbackResult
	{
		
		private int _id_feedback;
		
		private string _usuario;
		
		private string _comentario;
		
		private System.Nullable<int> _calificacion;
		
		private System.Nullable<System.DateTime> _fecha;
		
		public spObtenerFeedbackResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_feedback", DbType="Int NOT NULL")]
		public int id_feedback
		{
			get
			{
				return this._id_feedback;
			}
			set
			{
				if ((this._id_feedback != value))
				{
					this._id_feedback = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this._usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comentario", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string comentario
		{
			get
			{
				return this._comentario;
			}
			set
			{
				if ((this._comentario != value))
				{
					this._comentario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calificacion", DbType="Int")]
		public System.Nullable<int> calificacion
		{
			get
			{
				return this._calificacion;
			}
			set
			{
				if ((this._calificacion != value))
				{
					this._calificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
	}
	
	public partial class spObtenerReservasResult
	{
		
		private int _id_reserva;
		
		private int _id_cliente;
		
		private System.DateTime _fecha_reserva;
		
		private int _numero_personas;
		
		private string _estado;
		
		private string _nombre_cliente;
		
		public spObtenerReservasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_reserva", DbType="Int NOT NULL")]
		public int id_reserva
		{
			get
			{
				return this._id_reserva;
			}
			set
			{
				if ((this._id_reserva != value))
				{
					this._id_reserva = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int NOT NULL")]
		public int id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this._id_cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_reserva", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_reserva
		{
			get
			{
				return this._fecha_reserva;
			}
			set
			{
				if ((this._fecha_reserva != value))
				{
					this._fecha_reserva = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_personas", DbType="Int NOT NULL")]
		public int numero_personas
		{
			get
			{
				return this._numero_personas;
			}
			set
			{
				if ((this._numero_personas != value))
				{
					this._numero_personas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(50)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_cliente", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_cliente
		{
			get
			{
				return this._nombre_cliente;
			}
			set
			{
				if ((this._nombre_cliente != value))
				{
					this._nombre_cliente = value;
				}
			}
		}
	}
	
	public partial class spObtenerFacturaResult
	{
		
		private int _id_factura;
		
		private int _id_reserva;
		
		private int _numeroMesa;
		
		private string _listaPlatos;
		
		private string _listaPrecios;
		
		private decimal _total;
		
		private System.Nullable<System.DateTime> _fecha_facturacion;
		
		private string _nombre_cliente;
		
		private System.DateTime _fecha_reserva;
		
		public spObtenerFacturaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_factura", DbType="Int NOT NULL")]
		public int id_factura
		{
			get
			{
				return this._id_factura;
			}
			set
			{
				if ((this._id_factura != value))
				{
					this._id_factura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_reserva", DbType="Int NOT NULL")]
		public int id_reserva
		{
			get
			{
				return this._id_reserva;
			}
			set
			{
				if ((this._id_reserva != value))
				{
					this._id_reserva = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroMesa", DbType="Int NOT NULL")]
		public int numeroMesa
		{
			get
			{
				return this._numeroMesa;
			}
			set
			{
				if ((this._numeroMesa != value))
				{
					this._numeroMesa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_listaPlatos", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string listaPlatos
		{
			get
			{
				return this._listaPlatos;
			}
			set
			{
				if ((this._listaPlatos != value))
				{
					this._listaPlatos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_listaPrecios", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string listaPrecios
		{
			get
			{
				return this._listaPrecios;
			}
			set
			{
				if ((this._listaPrecios != value))
				{
					this._listaPrecios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(10,2) NOT NULL")]
		public decimal total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_facturacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_facturacion
		{
			get
			{
				return this._fecha_facturacion;
			}
			set
			{
				if ((this._fecha_facturacion != value))
				{
					this._fecha_facturacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_cliente", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_cliente
		{
			get
			{
				return this._nombre_cliente;
			}
			set
			{
				if ((this._nombre_cliente != value))
				{
					this._nombre_cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_reserva", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_reserva
		{
			get
			{
				return this._fecha_reserva;
			}
			set
			{
				if ((this._fecha_reserva != value))
				{
					this._fecha_reserva = value;
				}
			}
		}
	}
	
	public partial class spIniciarSesionResult
	{
		
		private string _nombre;
		
		private string _correo;
		
		private string _contrasena;
		
		public spIniciarSesionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this._contrasena = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
